apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: mirakurun
    tuner: dvb
  name: mirakurun-dvb
spec:
  selector:
    matchLabels:
      app: mirakurun
      tuner: dvb
  template:
    metadata:
      labels:
        app: mirakurun
        tuner: dvb
    spec:
      tolerations:
        - effect: NoSchedule
          key: node-role/baremetal
          value: "true"
      nodeSelector:
        tuner: dvb
      containers:
      - image: chinachu/mirakurun:3.9.0-rc.4
        command:
          - sleep
          - infinity
        imagePullPolicy: Always
        name: api
        securityContext:
          privileged: true
        env:
        - name: TZ
          value: Asia/Tokyo
        ports:
        - containerPort: 40772
          name: mirakurun
          protocol: TCP
        - containerPort: 9229
          name: unknown
          protocol: TCP
        volumeMounts:
        - mountPath: /dev/dvb
          name: devdvb
      volumes:
      - name: devbus
        hostPath:
          path: /dev/bus
      - name: devdvb
        hostPath:
          path: /dev/dvb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mirakurun
    tuner: dvb
  name: mirakurun-dvb
spec:
  type: ClusterIP
  ports:
  - name: mirakurun
    port: 40772
    protocol: TCP
  - name: unknown
    port: 9229
    protocol: TCP
  selector:
    app: mirakurun
    tuner: dvb
