apiVersion: kubedb.com/v1alpha2
kind: MySQL
metadata:
  name: epgstation-db
  namespace: default
spec:
  version: "5.7.31"
  storageType: Durable
  storage:
    storageClassName: "rook-ceph-block"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  podTemplate:
    spec:
      env:
      - name: TZ
        value: Asia/Tokyo
      - name: MYSQL_DATABASE
        value: epgstation
      args:
      - --character-set-server=utf8mb4
      - --default-time-zone=Asia/Tokyo
  terminationPolicy: Delete
