apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: mirakurun
    tuner/px4: "true"
  name: mirakurun-px4
  namespace: default
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mirakurun
      tuner/px4: "true"
  template:
    metadata:
      labels:
        app: mirakurun
        tuner/px4: "true"
    spec:
      containers:
      - env:
        - name: TZ
          value: Asia/Tokyo
        image: chinachu/mirakurun
        imagePullPolicy: Always
        name: api
        ports:
        - containerPort: 40772
          name: mirakurun
          protocol: TCP
        - containerPort: 9229
          name: unknown
          protocol: TCP
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app-config
          name: app-config
        - mountPath: /dev/px4video0
          name: devpx4video0
        - mountPath: /dev/px4video1
          name: devpx4video1
        - mountPath: /dev/px4video2
          name: devpx4video2
        - mountPath: /dev/px4video3
          name: devpx4video3
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - cp
        - /src/tuners.yml
        - /dst/tuners.yml
        image: busybox
        imagePullPolicy: Always
        name: cp
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /src
          name: mirakurun-config
        - mountPath: /dst
          name: app-config
      - command:
        - cp
        - /usr/local/bin/recpt1
        - /dst/
        image: ghcr.io/takutakahashi/recpt1-build:8ea6ab36bd273b8e4e5b2b15d04c00406d4abe2e
        imagePullPolicy: Always
        name: cp-recpt1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /dst
          name: app-config
      nodeSelector:
        tuner/px4: "true"
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role/baremetal
        operator: Equal
        value: "true"
      volumes:
      - name: app-config
      - configMap:
          defaultMode: 420
          name: mirakurun-px4-config
        name: mirakurun-config
      - hostPath:
          path: /dev/bus
          type: ""
        name: devbus
      - hostPath:
          path: /dev/px4video0
          type: ""
        name: devpx4video0
      - hostPath:
          path: /dev/px4video1
          type: ""
        name: devpx4video1
      - hostPath:
          path: /dev/px4video2
          type: ""
        name: devpx4video2
      - hostPath:
          path: /dev/px4video3
          type: ""
        name: devpx4video3
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
