apiVersion: v1
kind: Service
metadata:
  labels:
    app: mirakurun
  name: mirakurun
spec:
  type: ClusterIP
  ports:
  - name: mirakurun
    port: 40772
    protocol: TCP
  - name: unknown
    port: 9229
    protocol: TCP
  selector:
    app: mirakurun
