apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: toucher
  name: toucher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toucher
  template:
    metadata:
      labels:
        app: toucher
    spec:
      nodeSelector:
        kubernetes.io/hostname: node01
      containers:
      - image: ubuntu
        imagePullPolicy: Always
        name: app
        command:
          - bash
          - -c
          - "while true; do rm -f /mnt/touch; touch /mnt/touch; sleep 5; done"
        volumeMounts:
        - mountPath: /mnt
          name: vol
      volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: toucher
