resources:
  - ssh-host-key.yaml
  - workspace.yaml
  - workspace-backup-env.sealedsecret.yaml
  - backup-credentials.sealedsecret.yaml
  - service.yaml
  - service-mosh.yaml
configMapGenerator:
  - name: setup-ssh
    files:
      - setup-ssh.sh
