apiVersion: v1
kind: Service
metadata:
  name: workspace-mosh
  namespace: default
  annotations:
    metallb.universe.tf/allow-shared-ip: "workspace-10.30.0.12"
spec:
  type: LoadBalancer
  selector:
    app: workspace
  ports:
    - name: udp1
      port: 60001
      protocol: UDP
    - name: udp2
      port: 60002
      protocol: UDP
    - name: udp3
      port: 60003
      protocol: UDP
    - name: udp4
      port: 60004
      protocol: UDP
    - name: udp5
      port: 60005
      protocol: UDP
