apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: workspace
  name: workspace
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workspace
  serviceName: workspace
  template:
    metadata:
      labels:
        app: workspace
    spec:
      serviceAccount: workspace
      containers:
      - command:
        - /home/owner/.dev/bin/entrypoint-sshd
        env:
        - name: AUTHORIZED_KEYS_URL
          value: https://github.com/takutakahashi.keys
        image: ghcr.io/takutakahashi/workspace:b48e20f6f36859393671ecb57d728a93d803f66d
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 2
            memory: 8Gi
        name: workspace
        volumeMounts:
        - mountPath: /home/owner
          name: home
      initContainers:
      - command:
        - rsync
        - -av
        - /home/owner/
        - /tmp/owner
        image: ghcr.io/takutakahashi/workspace:b48e20f6f36859393671ecb57d728a93d803f66d
        imagePullPolicy: IfNotPresent
        name: cp
        volumeMounts:
        - mountPath: /tmp/owner
          name: home
      nodeSelector:
        workspace: "true"
      restartPolicy: Always
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: home
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      volumeMode: Filesystem
