apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-pat
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: ghcr-pat
    creationPolicy: Owner
  data:
  - secretKey: GITHUB_TOKEN
    remoteRef:
      key: ghcr-pat
      property: ghcr-pat
  - secretKey: password
    remoteRef:
      key: ghcr-pat
      property: ghcr-pat
  - secretKey: username
    remoteRef:
      key: ghcr-pat
      property: username
