apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-rollout
rules:
- apiGroups:
  - 'apps'
  resources:
  - 'deployments'
  - 'daemonsets'
  - 'statefulsets'
  verbs:
  - 'patch'
  - 'get'
