apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: openebs-zfs-node
  namespace: kube-system
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: zfs.openebs.io/fastpool
                operator: In
                values:
                  - "true"
