apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: public-github
  namespace: gitpod
spec:
  encryptedData:
    provider: AgBBQGAOe/FrCoShjpyjFS2IJHe/z27d2kbJyuYdSQNWzAbVzj8N5+qUqSY1903UfhgEjEnTyT0CIsATQp/rkRLNfuR9B0EXXi0y7B5YiUWq89bfXA0NdFVcPd4mJtECmNn+tLtoIdIO2QPnrhA0JRDhJPdOo74ajG1gcVCWalJvafKoMzYGQjHhIQJKCEMFrDSAi8yZv8Xb3juSh9zcGW6CjocJhfCIa0pnRAG76mnJIPv0Z5hTk4BG+aEN1dJmPsa6T6bL7uPtE8t7cIPb3kLl2o7zpvmWoGOsvM2IuSoTt2/CpOprDZGBfUmBlLvYHy9k1/lgZhjT+GwL9fYEi7Fe0/9lT89bc2ASfwXoilKY5twouY/mnQUp1KRT5g8LlAwRe/m2liqxX3ZI4EeJEdOBT8YsQVqxk98yBoS7pLwO51C1aPFFgZtMnAHEL5gss3+6f23fAPAQ+oKu+JAmuUCfjHPE9V8MdwdDo28beNLsvwgBvwROeqZXy/DglxEFkar1NagpgDTGtaUMZWYG2eaYhIEWtbTM2OvRQzsXDF9w6D1k0KdGbfxpw3H085EwCLVgNvL/yHAUqLXDnM9jO8+T29C4WYWPPlqsyzBDEtsM93MRS7uLogITDjEqpNGK18oR5UsdIJZQSPt8CgNv9Bj3L0uDaegtwuakAgJOm+By/nQowCQjYAhAf8/0T9Jlxa6H2F8b+j2ru/S2zgin+0ChmJvk+8BiuGIby8t1qsfKY/2F1W/J/SHbq5oslqivwCcZLlnGuNKGa8t5QqwBV4kn5927t98PCspOMSTXkvHYHfMdys01AhqvnItrFmwzHJds6xCftNW7uLiku4elhpXS13sW8FPT0Nw1OragPHLe5vr2smtTgQ8IZBGIIJkjL9dA7N5DnR8M2MmEkuOXcTIV+flk+DLuc0Egb+2bO2RLaAFOI7JFbhMlWGkQCzG03xMTj75DMye/So4YVfoo+ae7NEt2FuMZhKTZtUm7r8k20k7Woesikw/VAWGn9is6RRlZWgv7p9C5fbsOrApdzQ==
  template:
    metadata:
      creationTimestamp: null
      name: public-github
      namespace: gitpod

