allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fastpool
parameters:
  compression: "off"
  dedup: "off"
  fstype: ext4
  poolname: fastpool
  recordsize: 4k
provisioner: zfs.csi.openebs.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: zfs.openebs.io/fastpool
    values:
    - "true"
