apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: proxysql
  template:
    metadata:
      labels:
        app: proxysql
    spec:
      initContainers:
      - name: generate-proxysql-config
        image: bhgedigital/envsubst
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - envsubst < /mnt/proxysql.cnf > /etc/proxysql/proxysql.cnf
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: proxysql-secret
              key: db-password
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: proxysql-secret
              key: db-username
        volumeMounts:
        - name: proxysql-config-volume
          mountPath: /mnt
        - name: proxysql-config-output
          mountPath: /etc/proxysql
      containers:
      - name: proxysql
        imagePullPolicy: IfNotPresent
        image: proxysql/proxysql:latest
        volumeMounts:
        - name: proxysql-config-output
          mountPath: /etc/proxysql.cnf
          subPath: proxysql.cnf
        ports:
        - containerPort: 6032 # Admin interface
        - containerPort: 6033 # MySQL interface
      volumes:
      - name: proxysql-config-volume
        configMap:
          name: proxysql-config
      - name: proxysql-config-output
        emptyDir: {}
