apiVersion: v1
kind: Service
metadata:
  name: proxysql
spec:
  type: LoadBalancer
  selector:
    app: proxysql
  ports:
  - name: admin
    port: 6032
    targetPort: 6032
  - name: mysql
    port: 6033
    targetPort: 6033
