apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: node-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  tolerations:
    - effect: NoSchedule
      key: node-role/home
      value: "true"
    - effect: NoExecute
      key: k3s-controlplane
      value: "true"
    - effect: NoSchedule
      key: node-role/storage
      value: "true"
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  version: v1.25.14+k3s1
