apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stf
  name: stf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stf
  template:
    metadata:
      labels:
        app: stf
    spec:
      containers:
      - image: devicefarmer/stf:3.6.1
        imagePullPolicy: Always
        name: app
        command:
        - stf
        - local
        - --adb-host
        - 10.10.1.72
        - --public-ip
        - 10.10.0.165
        - --provider-min-port
        - "31600"
        - --provider-max-port
        - "31610"
