apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airsonic-config
spec:
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
