apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lab-takutakahashi-dev-route53-secret
  namespace: cert-manager
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: lab-takutakahashi-dev-route53-secret
    creationPolicy: Owner
  data:
  - secretKey: secret-access-key
    remoteRef:
      key: lab-takutakahashi-dev-route53-secret
      property: aws_secret_access_key
