---
# Source: sshpiper/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sshpiper-reader
  labels:
    helm.sh/chart: sshpiper-0.3.1
    app.kubernetes.io/name: sshpiper
    app.kubernetes.io/instance: sshpiper
    app.kubernetes.io/version: "1.2.3"
    app.kubernetes.io/managed-by: Helm
---
# Source: sshpiper/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sshpiper-server-key
  labels:
    helm.sh/chart: sshpiper-0.3.1
    app.kubernetes.io/name: sshpiper
    app.kubernetes.io/instance: sshpiper
    app.kubernetes.io/version: "1.2.3"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  server_key: "LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU8xTk1WVVhzMlRia2NwZHdBa20vU3NWTVI4aDRSM1QxQzJ4NEx2WktUTStvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFREtWUnpwSFgvVVpxb0kzZUU5RTRUeUE4SERGMWRYWnpGSVhlL1BNd2lSdkZ4aDVsSjlJTwpZVzB2MktpK3JNeGYyVlhySFpVWTZxNlVXd3B2WloxcDJBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo="
---
# Source: sshpiper/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sshpiper
  labels:
    helm.sh/chart: sshpiper-0.3.1
    app.kubernetes.io/name: sshpiper
    app.kubernetes.io/instance: sshpiper
    app.kubernetes.io/version: "1.2.3"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - sshpiper.com
  resources:
  - pipes
  verbs:
  - get
  - list
  - watch
---
# Source: sshpiper/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sshpiper
  labels:
    helm.sh/chart: sshpiper-0.3.1
    app.kubernetes.io/name: sshpiper
    app.kubernetes.io/instance: sshpiper
    app.kubernetes.io/version: "1.2.3"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sshpiper
subjects:
  - kind: ServiceAccount
    name: sshpiper-reader
    namespace: "sshpiper"
---
# Source: sshpiper/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sshpiper
  labels:
    helm.sh/chart: sshpiper-0.3.1
    app.kubernetes.io/name: sshpiper
    app.kubernetes.io/instance: sshpiper
    app.kubernetes.io/version: "1.2.3"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 2222
      targetPort: 2222
      protocol: TCP
      name: sshpiper
  selector:
    app.kubernetes.io/name: sshpiper
    app.kubernetes.io/instance: sshpiper
---
# Source: sshpiper/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshpiper
  labels:
    helm.sh/chart: sshpiper-0.3.1
    app.kubernetes.io/name: sshpiper
    app.kubernetes.io/instance: sshpiper
    app.kubernetes.io/version: "1.2.3"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sshpiper
      app.kubernetes.io/instance: sshpiper
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sshpiper
        app.kubernetes.io/instance: sshpiper
    spec:
      serviceAccountName: sshpiper-reader
      securityContext:
        {}
      containers:
      - name: sshpiper
        image: "farmer1992/sshpiperd:1.2.3"
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
        ports:
          - containerPort: 2222
        env:
        - name: PLUGIN
          value: "kubernetes"
        - name: SSHPIPERD_SERVER_KEY
          value: "/serverkey/ssh_host_key"
        - name: SSHPIPERD_LOG_LEVEL
          value: "info"
        - name: SSHPIPERD_LOGIN_GRACE_TIME
          value: "30s"
        volumeMounts:
        - name: sshpiper-server-key
          mountPath: "/serverkey/"
          readOnly: true
        resources:
          {}
      volumes:
      - name: sshpiper-server-key
        secret:
          secretName: sshpiper-server-key
          items:
          - key: server_key
            path: ssh_host_key

