prometheus:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - prom.in.takutakahashi.dev
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
nodeExporter:
  tolerations:
  - effect: NoExecute
    key: kubernetes.io/arch
    operator: Equal
    value: arm
