prometheus:
  ingress:
    enabled: true
    hosts:
      - prom.in.takutakahashi.dev
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
nodeExporter:
  tolerations:
  - effect: NoExecute
    key: kubernetes.io/arch
    operator: Equal
    value: arm
