prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
nodeExporter:
  tolerations:
  - effect: NoExecute
    key: kubernetes.io/arch
    operator: Equal
    value: arm
