apiVersion: v1
kind: Service
metadata:
  annotations:
    zerotier.takutakahashi.dev/enable: "true"
  labels:
    app: bastion
  name: bastion
spec:
  type: ClusterIP
  ports:
  - name: ssh
    protocol: TCP
    port: 22
  selector:
    app: bastion
