# Copyright (c) 2021 Tailscale Inc & AUTHORS All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: subnet-router
spec:
  replicas: 1
  serviceName: "subnet-router"
  selector:
    matchLabels:
      app: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      serviceAccountName: tailscale
      volumes:
        - name: run
          configMap:
            name: tailscale-run
      initContainers:
      - name: sysctler
        image: busybox
        securityContext:
          privileged: true
        command: ["/bin/sh"]
        args:
          - -c
          - sysctl -w net.ipv4.ip_forward=1
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
      containers:
      - name: tailscale
        imagePullPolicy: Always
        image: ghcr.io/tailscale/tailscale:latest
        volumeMounts:
          - name: run
            mountPath: /opt
        command:
          - sh
          - /opt/run.sh
        env:
        # Store the state in a k8s secret
        - name: KUBE_SECRET
          value: tailscale-auth
        - name: USERSPACE
          value: "true"
        - name: AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: AUTH_KEY
              optional: true
        - name: ROUTES
          value: "10.10.0.0/22"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
