apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: diary-assets
  namespace: blog
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ephemeral-rwx
