apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: diary-assets-2
  namespace: blog
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-csi
