apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: diary
    role: worker
  name: diary-worker
  namespace: blog
spec:
  schedule: "0 * * * *"
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: diary
            role: worker
        spec:
          restartPolicy: Never
          containers:
          - envFrom:
            - secretRef:
                name: diary-secret
            env:
            - name: BLOG_TITLE
              value: diary.takutakahashi.dev
            - name: BLOG_URL
              value: diary.takutakahashi.dev
            - name: BLOG_GA
              value: "G-P6ESSZ61CV"
            - name: BLOG_THEME_URL
              value: "https://github.com/takutakahashi/hugo-theme-anubis.git"
            - name: ONCE
              value: "--once"
            image: ghcr.io/takutakahashi/blog.tpl:v1.10.0
            imagePullPolicy: Always
            name: worker
            volumeMounts:
            - mountPath: /src/public
              name: public
            - mountPath: /src/images
              name: images
            - mountPath: /src/content/posts
              name: content
          volumes:
          - name: public
            persistentVolumeClaim:
              claimName: diary-assets-2
          - name: images
            persistentVolumeClaim:
              claimName: image-assets-3
          - emptyDir: {}
            name: content
