apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: workspace
  namespace: default
spec:
  dnsNames:
  - '*.ws.lab.takutakahashi.dev'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: workpsace
