apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  annotations:
    metallb.universe.tf/address-pool: bgp-pool
  namespace: ingress
spec:
  ports:
    - name: metrics
      port: 10254
      protocol: TCP
      targetPort: 10254
      appProtocol: http
