apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics
  namespace: ingress
spec:
  endpoints:
  - interval: 10s
    port: metrics
    path: /metrics
  namespaceSelector:
    matchNames:
    - ingress
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/component: controller
