apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-token
  namespace: oci-image-operator-system
spec:
  data:
  - remoteRef:
      key: oci-image-operator-github-com
      property: GITHUB_TOKEN
    secretKey: GITHUB_TOKEN
  - remoteRef:
      key: oci-image-operator-github-com
      property: username
    secretKey: username
  - remoteRef:
      key: oci-image-operator-github-com
      property: GITHUB_TOKEN
    secretKey: password
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: github-token
