apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devblog
    role: worker
  name: devblog-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devblog
      role: worker
  template:
    metadata:
      labels:
        app: devblog
        role: worker
    spec:
      volumes:
      - name: public
        persistentVolumeClaim:
          claimName: techblog-assets
      - name: content
        emptyDir: {}
      initContainers:
      - image: takutakahashi/blog
        imagePullPolicy: Always
        name: mv
        command:
          - bash
          - -c
          - "mv /src/content/posts/* /content"
        volumeMounts:
        - mountPath: /content
          name: content
      containers:
      - image: takutakahashi/blog
        imagePullPolicy: Always
        name: worker
        command:
          - notion-tpl
          - --table-id
          - $(TABLE_ID)
          - --token
          - $(TOKEN)
          - --export-path
          - /src/content/posts
          - --template
          - /etc/notion-tpl/hugo.md.tpl
          - --cmd
          - hugo
        volumeMounts:
        - mountPath: /src/public
          name: public
        - mountPath: /src/content/posts
          name: content
        envFrom:
        - secretRef:
            name: devblog-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devblog
    role: web
  name: devblog-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devblog
      role: web
  template:
    metadata:
      labels:
        app: devblog
        role: web
    spec:
      volumes:
      - name: public
        persistentVolumeClaim:
          claimName: techblog-assets
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: server
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: public
