apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: devblog-secret
  namespace: default
spec:
  encryptedData:
    TABLE_ID: AgBwxnUQoz6lmu0nWNii8UqT1pZ0yjnsr4m7zWvIWT10xTvqkBA7iBbKz4KU3T2dxYnROizDlBJzWMhRSHRcg6fUOZn7KU+KdofwNoeDQyuL4kp74G6IwETL6ba2rNhpVjJBo48+SvJETSv70Yx8NMittq5je5GFRhE37e6xbbyZ3NuZX1FNqOL+qUIbu8JipdCtgpqvP1HdgQopUen8k9Dg3DkpPGiWX6DFvRi6EWtbKJUoZlcenPzWjRhrEyHmQA+6EKkvXPMzs1buyfTf6BB4UslWMJOfC0VfMbli0qMXYkI/3s8qtYLpNo8/xxroge9b6p/RTUJQhfAOm8EEr/GKlAIAy9bqZxyNb1DegVQnVHanCyaC+Pzp8wSOGOWsUVBxGSJRykhGlE1lYvjUC+KDvwMdkQB3ZvCxbKMB7xSRyhUaTD4d6JBaw7QrA0TjzZoBZKxt+yOnzLTw/QDg22rHPK2Gfw6SUJx7ubiw+8cCI5fnFPgVEa/LyBfBkv1fMxxY+i3v27W3Zs7LKVCT9mGaAiXXdUhBGb7yNkRrq0c9dqAS6A5wtns1vmjRP8HvGZnKKm7OTJhHLi48VCLblQH2cCY+vB5/QGfcnZqg2UY0pkvzUdf048UQeATQ4m4Tsq8VPSBs4FvtPsWdq4Zc79uDpIPaKRTsxGt/3q4DxCikl410O/NTlBewR/D3OvlaH4ilQkp0Lji30IlIgqyMZ01uIoKhTSNGaTsVTGKDiNnc6Q==
    TOKEN: AgCAjfOZ5BJ0OF5xc5AVcZsgb2/WCZWuS53jRvjaSlToH6dR0VllQeb7euv69jCcoeJq+CjvhYSBWIwLJD8/0arWDF8B2+4lsiNAj+72CTi67qAyuPeDAC+NQVVreD1PFu9djY/xY0Q2IU/blbL9oF6BKhsQyOh1V+WvsavIHpkeiBtUnfaYDkMz8XhQAmOa3kCqHfWznJrOliPhYbECOnbBE3qXAQiRSN2QO3M94dSyz+09QPqfDTl1+ck/xBP0pY2zHjWVYcANLRPvhmcgmMf+OsumRB4oHfujXGlo+cPLLP0PcosebZJoIyvxmNIoB5lyVYUEQ2M9QFpLU40EEGsahqs3kpyLvRAjHLR8oHa3UyCHSQO2VbimEPguqOW4ZUTynmoh5R1ikqZGGWEQH1YejuA0j+2ZT5JiPCTNbe2dxcy68pWjoBGZqR6U54KrnksUM8ffFCJ8sKRDIzCPaLyj3rjKS/xS8x+mrCdszIQYvCmWd/uZwvTHbnyK8x8gG7aINwUiNttpW4c6l+hIj0kOOX0Ue4ojngIvTFa69jfytQKu03jVUHAAmViDIRMAZuYO7St4XxW75zm6evb0tK62baSiRR84TDNWF6cnEEljM18gwUICTxAYNX0vUYqxqobddQ0lzfWIo93B5KvlPSBXAXOU3JvCrN0VhIyDztSGJvVEj6Lxj5t5xluqspwOik3d0ATksEQS73YhMzo/AdEUy2smkITTfwti17TQk5mFoVyyKF/JKJ8Bqt52O8k55NrQyNrjS1fgXURa21pu5tGHjFjC5Yfm2vvQVmY+OXQ4URBTw3BVC9AwgI4AnLILNqE33DFbhLjiZwzBxFZtDLUjY+jOUqzG91MQ0d5rttdCxCcxs20XiN3zyAXzhkdQKlxLYya+upJNYgiz8Vw=
  template:
    metadata:
      creationTimestamp: null
      name: devblog-secret
      namespace: default
    type: Opaque

