apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: techblog-assets
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ephemeral-rwx
