apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/production
    repoURL: https://github.com/takutakahashi/testbed.git
    targetRevision: release
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
