apiVersion: v1
kind: Service
metadata:
  labels:
    app: adb
  name: adb
spec:
  ports:
  - name: port1
    port: 5037
    protocol: TCP
  - name: port2
    port: 5555
    protocol: TCP
  selector:
    app: adb
  type: LoadBalancer
