apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infra/cert-manager
    repoURL: https://github.com/takutakahashi/testbed.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
