apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  destination:
    namespace: monitor
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infra/external-dns
    repoURL: https://github.com/takutakahashi/testbed.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
