apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitor
  namespace: argocd
spec:
  destination:
    namespace: monitor
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "40.3.1"
    chart: kube-prometheus-stack
    helm:
      releaseName: prometheus-stack
      
      values: |
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
        nodeExporter:
          tolerations:
          - effect: NoExecute
            key: kubernetes.io/arch
            operator: Equal
            value: arm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Replace=true
