apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-operator
  namespace: argocd
spec:
  destination:
    namespace: mysql-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infra/mysql-operator
    repoURL: https://github.com/takutakahashi/testbed.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
