apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: autobuy
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: buy
            image: takutakahashi/autobuy
            envFrom:
            - secretRef:
                name: autobuy-secret
            args:
            - python
            - app.py
            - --ticker
            - ETH_JPY
            - --jpy
            - "500"

          - name: buy-btc
            image: takutakahashi/autobuy
            envFrom:
            - secretRef:
                name: autobuy-secret
            args:
            - python
            - app.py
            - --ticker
            - BTC_JPY
            - --jpy
            - "1500"

