apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: autobuy-secret
  namespace: default
spec:
  encryptedData:
    API_KEY: AgCPNOtZEKKSFs+MfWz4J0J/jmTiFh/dYG6XYoDu8j03uuNYtXyvyJq/Y0m4eNrVJzysO2wnkppY+tPMj2IwzaQyDbi8lOFqj9w8obqwyVqUZNYfQUGr567ljLkQAA71CYSfaNUBIrPqU5N4RtdZ5CDTdBkeg5HUEq3shXP9cRT03YPDDyNn0t/hFTHP0bnlnckvrkCq6M7AIaJaNfOxGvnwiFJb86KtZ8wGhQD9iAAXCwWmgc834+z1xAYDmInx0iOnDlS8wmTz5C33K6tSCoj9Zt0/ngvIT1BDT7z9lOYRkoAunrYlaLqD84FylahPE/NmP6pi9O6fO1dB8i9a3zhXOUpP84e2YXcH8oW0O//JfbgG71TwjhqZ1TTqOH7kUz6uuTjA1eCrnnLZgDo5OoKG/Ij2xpBv135pzEiOAzvfdoKoQnwQ17ARKUxRxRXN22/t/LW5WDa1kEA3QavqmbxVi6eiTt0NWnxrk6uURDKnoxuy8G2CpZ+ZHTkQxSYJ+O4qk6DuxgLn1BJvXvPZnFlblTsnai7PmTm+s9lgQeXNLClJCGmpnp13I11973bMMZVtEL1UAzIOxa3tpcZLeKcOsdupGIdQbbpVxBB5U9sPGxQ+OcBioFHotdnuzqm5u3cRlwc/GSFxcVV1Z1zfOSNr4Ewls0j7/qOHkY2MnwBoeyb48dzxTrv9P3ehNS2Wt0zKvGJhnA53rZA6qPsY9efgRwylHTuU
    API_SECRET: AgBVraJ53zOsVfzDhKEjESS4WGHC924u8gJp9nrHkexp6yd60/n+Vd0hhCqblDyumM40p/mE5y+wnQZJWD9FE+83r2ZUKN65e39bEHR4dmatJ9aJTP5AA6JY920XInTGAX1wjfNiOSToL9YLh1E2YhOfUAQr8rUOTRCkNNP61LG71DJTQWgH9FpA5ft1J1TYyjWrEaQXlWersbFnfx5qj5IF9MvgHZ6HVz8Z2RXN3ri+7s7QPB3YO65/ChdfRTI3NssbDnQ1REGyhZrbO5sQSc6p8IIjS8UPwAzjFcXCXbwWoAfbIbllJCTu3vH4ZDJVH0ATHvjQ2bjbQHdkQ36Y+ED62BQCvi28b+ohLNQ8OWXTQFvRwRYZj5UU5ICHjaIYu9AY61v6TXspLAqj5e3ymkWl5UlXBobrDz/s2uODrmToqFcddm8OAIdqqvraFjtmz3kb2PV03VTk9b+abtib4wbu6uC5v7YxwlnpnTkIQmKFHT4/XqHy1U+7rIMB4jKPdj/rXSwKOyN3RMSAolUAFLnrgeGZvD0eqPds5K/kW4ivchRwpWHUTfEJhlqth9BfsRwFUJD6d364waVqk4t593uO/vfIbGHzw6dyLnDyLMxT9H+F84KKQphfNY4yXs+3bfmcXdekSb6VC9yHzuNucNXdFNyJVO4I4OLo+jAl2jAt4MQR6cBC7CTvRzu9UriHAHCfjiGXD+3Ui7qRkjHfjYdjvbXmQgK6mqF3deQh5fQrhx7NEo3dh449wZsfsg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: autobuy-secret
      namespace: default
    type: Opaque

