apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-tls-secret
spec:
  dnsNames:
  - cloak.takutakahashi.dev
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  secretName: cluster-tls-secret
