longhornManager:
  tolerations:
    - effect: NoSchedule
      key: node-role/storage
      value: "true"
longhornDriver:
  tolerations:
    - effect: NoSchedule
      key: node-role/storage
      value: "true"
longhornUI:
  tolerations:
    - effect: NoSchedule
      key: node-role/storage
      value: "true"

ingress:
  enabled: true
  host: longhorn.in.takutakahashi.dev
  tls: true
  ingressClassName: nginx
  tlsSecret: longhorn-ui
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
