apiVersion: apps/v1
kind: Deployment
metadata:
  name: pritunl
  labels:
    app: pritunl
spec:
  selector:
    matchLabels:
      app: pritunl
  template:
    metadata:
      labels:
        app: pritunl
    spec:
      containers:
        - name: pritunl
          image: goofball222/pritunl:latest
          securityContext:
            privileged: true
          env:
          - name: MONGODB_URI
            value: mongodb://mongodb:27017/pritunl
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    zerotier.takutakahashi.dev/enable: "true"
    zerotier.takutakahashi.dev/hostname: vpn.zt.lab.takutakahashi.dev
  labels:
    app: pritunl
  name: pritunl
spec:
  type: LoadBalancer
  loadBalancerIP: 10.30.0.100
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP
  - name: openvpn-tcp
    port: 1194
    protocol: TCP
  - name: openvpn-udp
    port: 1194
    protocol: UDP
  - name: wireguard-udp
    port: 1195
    protocol: UDP
  - name: web
    port: 9700
    protocol: TCP
  selector:
    app: pritunl

