apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: db-secret
spec:
  encryptedData:
    password: AgBAWJm/AALES629bZEbp3YOBM0GHJOS8QyIxX/MA+DwUDvEd82I6CiwGX2NaM1ZM1KQ9ToaNloHv3c6m0B58nL/FAJK+dUwxwvnfSAu/4AP+ejwqD9kiWPCRZocMCFG8yCd1e7VhfLwC3lWi1wGFR/UkNq1tEP6ycL9MLaNY1fVoKEuxoowG3Aa4Cf+tsWZYZg4vswQE/xFPuLIPnKlyAxHsYv0Yn+7IKuPQ6N5nzB9yZr2A9MUPlUH01wmcdS+DfFDcxLp5CAeAmA63ZAfeu2R0AIbEDS8pIYMBpktlJEB2ae3dXv0cG6TzvGHbhU31NlgGVfG8efyPjUdVGl+STjqU2i31uY3/QVB5dGsWmsVRS686AokUBIYE012IpUMs+/Cjocl5T/F0WON1LWYOciBgcEatSkmA9R0Jbc9a6zbv/OqbaqQE8bUuno1amvRcViTG6PVVhmFPUXLKavUfBc6RAd1GR2KGSp1VZQakZoDHslDPs87ggTLPr/u5X9a79rZdzaQo4F7SanmXjViMDSrI1HQjojY8oe0k3Xxy7xsj5eh+uowYpy8OC2PcSmlPNfnA2uETYBsgcfm21zRKDYRPN+1hdgGYSLZ3zWn3cU2z6zKDZLA+MJuh7ZwwYc7+bQom9r2t1qb/ZUqAZ0p2kwnik8yuZIU8KmQ0AAa/F2stWUYCI0Hs8pKmIPqJdgyY7nVxCdKaHzmItnxTiYX35ToaV/JoU8D
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: db-secret

