apiVersion: v1
kind: ConfigMap
metadata:
  name: z8r-config
  namespace: z8r
data:
  config.yaml: |
    - master: "kvm:tank/all"
      replica: "ws:backup/new/tank/all"
    - master: "kvm:tank/etc"
      replica: "ws:backup/tank/etc"
    - master: "kvm:tank/enctv"
      replica: "ws:backup/new/tank/enctv"
    - master: "kvm:tank/tv"
      replica: "ws:backup/new/tank/tv"
    - master: "ws:localpool/aki"
      replica: "ws:backup/localpool/aki"
  snapshot.yaml: |
    targets:
    - kvm:tank/all
    - kvm:tank/etc
    - kvm:tank/enctv
    - kvm:tank/tv
    - node02:fastpool/pv
    - ws:localpool/aki
