apiVersion: v1
kind: ConfigMap
metadata:
  name: z8r-config
  namespace: z8r
data:
  snapshot.yaml: |
    targets:
    - kvm:tank/all
    - kvm:tank/etc
    - kvm:tank/enctv
    - kvm:tank/tv
    - node02:fastpool/pv
    - node02:fastpool/tv
    - node02:fastpool/aki
  config.yaml: |
    - master: "kvm:tank/all"
      replica: "ws:backup/tank/all"
    - master: "kvm:tank/etc"
      replica: "ws:backup/tank/etc"
    - master: "kvm:tank/enctv"
      replica: "ws:backup/tank/enctv"
    - master: "kvm:tank/tv"
      replica: "ws:backup/tank/tv"
    - master: "node02:fastpool/pv"
      replica: "ws:backup/fastpool/pv"
    - master: "node02:fastpool/tv"
      replica: "ws:backup/fastpool/tv"
    - master: "node02:fastpool/aki"
      replica: "ws:backup/fastpool/aki"
