apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: z8r
    tier: daemon
  name: node-daemon
  namespace: z8r
spec:
  #  strategy:
  #    type: Recreate
  selector:
    matchLabels:
      app: z8r
      tier: daemon
  template:
    metadata:
      labels:
        app: z8r
        tier: daemon
    spec:
      serviceAccount: z8r
      nodeSelector:
        z8r: "true"
      volumes:
      - name: config
        configMap:
          name: z8r-config
      containers:
      - image: takutakahashi/z8r:v0.4.1
        imagePullPolicy: Always
        name: app
        securityContext:
          privileged: true
        command:
        - /entrypoint_daemon.sh
        volumeMounts:
        - name: config
          mountPath: /etc/z8r
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: replicator
  name: replicator
  namespace: z8r
spec:
  replicas: 1
  selector:
    matchLabels:
      app: replicator
  template:
    metadata:
      labels:
        app: replicator
    spec:
      serviceAccount: z8r
      volumes:
      - name: config
        configMap:
          name: z8r-config
      containers:
      - image: takutakahashi/z8r:v0.4.1
        imagePullPolicy: Always
        name: app
        volumeMounts:
        - name: config
          mountPath: /etc/z8r
        env:
          - name: DEBUG
            value: "false"
        command:
        - /entrypoint_replicator.sh
