apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: replicator
  name: replicator
  namespace: z8r
spec:
  schedule: "15 * * * *"
  suspend: false
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: replicator
        spec:
          restartPolicy: Never
          serviceAccount: z8r
          volumes:
          - name: config
            configMap:
              name: z8r-config
          - name: ssh-key
            secret:
              secretName: z8r-ssh-keys
          containers:
          - image: ghcr.io/takutakahashi/z8r:v0.7.0
            imagePullPolicy: Always
            name: app
            volumeMounts:
            - name: config
              mountPath: /etc/z8r
            - name: ssh-key
              mountPath: /opt/ssh
            env:
              - name: DEBUG
                value: "false"
              - name: REPLICATION_TYPE
                value: "rsync"
            command:
              - bash
              - -c
              - "cp /opt/ssh/id_rsa /root/.ssh && chmod 600 /root/.ssh/id_rsa && /entrypoint_replicator.sh"
