repositories:
  - name: teleport
    url: https://charts.releases.teleport.dev
releases:
  - name: teleport-cluster
    chart: teleport/teleport-cluster
    namespace: teleport
    values:
      - values.yaml
