apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitpod
    role: proxy
  annotations:
    oci-network-load-balancer.oraclecloud.com/security-list-management-mode: All
    oci.oraclecloud.com/load-balancer-type: nlb
  name: gitpod-proxy
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  - name: metrics
    port: 9500
  - name: sshd
    port: 2222
  selector:
    app: gitpod
    role: proxy
