apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rethinkdb
  name: rethinkdb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rethinkdb
  template:
    metadata:
      labels:
        app: rethinkdb
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: rethinkdb
      containers:
      - image: rethinkdb:2.3
        imagePullPolicy: Always
        name: db
        volumeMounts:
        - name: data
          mountPath: /data
        command:
        - rethinkdb
        - --bind
        - all
        - --cache-size
        - "2048"