apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rethinkdb
  name: rethinkdb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rethinkdb
  template:
    metadata:
      labels:
        app: rethinkdb
    spec:
      containers:
      - image: rethinkdb:2.3
        imagePullPolicy: Always
        name: db
        command:
        - rethinkdb
        - --bind
        - all
        - --cache-size
        - "2048"
