apiVersion: v1
kind: Service
metadata:
  labels:
    app: rethinkdb
  name: rethinkdb
spec:
  ports:
  - name: port1
    port: 28015
    protocol: TCP
  - name: port2
    port: 29015
    protocol: TCP
  - name: port3
    port: 8080
    protocol: TCP
  selector:
    app: rethinkdb
  type: ClusterIP
