postgresql:
  enabled: true
mariadb:
  enabled: false
ingress-nginx:
  enabled: false
cert-manager:
  enabled: false
database:
  type: postgresql
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt"
