apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: zrepl
    tier: daemon
  name: node-daemon
  namespace: zrepl
spec:
  selector:
    matchLabels:
      app: zrepl
      tier: test
  template:
    metadata:
      labels:
        app: zrepl
        tier: test
    spec:
      serviceAccount: zrepl
      nodeSelector:
        zrepl: "true"
      containers:
      - image: takutakahashi/zrepl
        imagePullPolicy: Always
        name: app
        securityContext:
          privileged: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: replicator
  name: replicator
  namespace: zrepl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: replicator
  template:
    metadata:
      labels:
        app: replicator
    spec:
      serviceAccount: zrepl
      nodeSelector:
        kubernetes.io/hostname: node01
      containers:
      - image: takutakahashi/zrepl
        imagePullPolicy: Always
        name: app
        command:
        - /replicator.sh
