apiVersion: v1
kind: Service
metadata:
  labels:
    app: zrepl-replicator
  name: zrepl-replicator
  namespace: zrepl
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: zrepl-replicator
