apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-assets
  namespace: blog
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ephemeral-rwx
