apiVersion: v1
kind: Service
metadata:
  labels:
    app: image
    role: web
  name: image-web
  namespace: blog
spec:
  ports:
  - name: image
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: image
    role: web
  type: ClusterIP
