apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: devblog
spec:
  tls:
  - hosts:
    - www.stg.in.takutakahashi.dev
    secretName: devblog-tls-secret
  rules:
  - host: www.stg.in.takutakahashi.dev
    http:
      paths:
      - path: /
        backend:
          serviceName: devblog-web
          servicePort: 80
